apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../../application


patchesStrategicMerge:
- deployment.yaml

patches:
- target:
    kind: LimitRange
    name: ecr-helm-limit-range
  patch: |-
    - op: replace
      path: /spec:/limits/default/cpu
      value: 1000      version: v1
      kind: LimitRange
      name: ecr-helm-limit-range

