apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../../application


helmCharts:
  - name: namespace-default
    valuesInline:
      namespace: ecr-helm
      ecrJob:
        enabled: true
    repo: https://saschaschuenemannpflegede.github.io/helmcharttest/
    releaseName: namespace-default-0.1.3