apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../../application


patchesStrategicMerge:
- deployment.yaml

patches:
 - target:
      version: v1
      kind: LimitRange
      name: ecr-helm-limit-range
   path: limit-patch.yaml