apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
patches:
- target:
    kind: LimitRange
    name: ecr-helm-limit-range
  patch: |-
    - op: replace
      path: /spec:/limits/default/cpu
      value: 1000
- path: deployment.yaml

resources:
- deployment.yaml
