apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../../application


#helmCharts:
#  - name: namespace-default
#    valuesInline:
#      namespace: ecr-helm
#      ecrJob:
#        enabled: false
#    repo: https://raw.githubusercontent.com/SaschaSchuenemannPflegede/argo-kustomize-helm-test/master/
#    releaseName: namespace-default-0.1.1