apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/component: service
  app.kubernetes.io/instance: ns-default-test
  app.kubernetes.io/managed-by: argocd
  app.kubernetes.io/part-of: ns-default-test
resources: 
  - base/namespace.yaml
#  - base/namespace-defaults.yaml

#generators:
#  - base/namespace-defaults.yaml

helmCharts:
  - name: namespace-default
    valuesFile: base/values.yaml
    repo: https://saschaschuenemannpflegede.github.io/helmcharttest/
    releaseName: namespace-default-0.1.3