apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/component: service
  app.kubernetes.io/instance: ns-default-test
  app.kubernetes.io/managed-by: argocd
  app.kubernetes.io/part-of: ns-default-test
resources: 
  - base/namespace.yaml

# outcomment if different configurations are desired for some environments
# in this case copy and paste this into the overlay kustomization file for your environments
helmCharts:
  - name: namespace-default
    valuesInline:
      namespace: ecr-helm
      ecrJob:
        enabled: true
      resourceQuota: # limit for aggregate resource consumption in the namespace
        requestsCpu: "2"
    repo: https://saschaschuenemannpflegede.github.io/helmcharttest/
    releaseName: namespace-default-0.1.3
