apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/component: service
  app.kubernetes.io/instance: ns-default-test
  app.kubernetes.io/managed-by: argocd
  app.kubernetes.io/part-of: ns-default-test
resources: 
  - base/namespace.yaml

#helmCharts:
#  - name: namespace-default
#    valuesInline:
#      namespace: ecr-helm
#      ecrJob:
#        enabled: false
#    repo: https://raw.githubusercontent.com/SaschaSchuenemannPflegede/argo-kustomize-helm-test/master/
#    releaseName: namespace-default-0.1.1